name: orange_planet_app
description: A new Flutter project.

version: 1.1.4+6

environment:
  sdk: ">=2.5.0 <3.0.0"

analyzer:
  enable-experiment:
    - control-flow-collections

dependencies:
  flutter:
    sdk: flutter
  material_design_icons_flutter: ^4.0.5045
  flutter_launcher_icons: ^0.7.5
  google_fonts: ^1.0.0
  grouped_buttons: ^1.0.4
  shared_preferences: ^0.5.7+3
  url_launcher: ^5.7.4
  flutter_svg: ^0.19.1
  firebase_admob: ^0.9.3

  cupertino_icons: ^0.1.2

flutter_icons:
  image_path: "icon/icon.png"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/bonfires/
    - assets/images/doctor/
    - assets/images/guitar/
    - assets/images/knots/
    - assets/images/navigator/
    - assets/images/photographer/
    - assets/images/repairMaster/
    - assets/images/sailor/
    - assets/images/sniper/
    - assets/songs/
    - icon/logoPrince.png
    - icon/icon.png

    